# Keep all in alphabetical order
components:
  providers/openfeature-flagd-provider:
    - toddbaert
    - josecolella
  providers/openfeature-flipt-provider:
    - falghi
  providers/openfeature-go-feature-flag-provider:
    - thomaspoignant
  providers/openfeature-meta_provider:
    - maxveldink
  providers/openfeature-flagsmith-provider:
    - dabeeeenster
    - matthewelwell
    - zaimwa9

ignored-authors:
  - renovate-bot
