# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema/v1/schema.proto

require "google/protobuf"

require "google/protobuf/struct_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("schema/v1/schema.proto", syntax: :proto3) do
    add_message "schema.v1.ResolveAllRequest" do
      optional :context, :message, 1, "google.protobuf.Struct", json_name: "context"
    end
    add_message "schema.v1.ResolveAllResponse" do
      map :flags, :string, :message, 1, "schema.v1.AnyFlag"
    end
    add_message "schema.v1.AnyFlag" do
      optional :reason, :string, 1, json_name: "reason"
      optional :variant, :string, 2, json_name: "variant"
      oneof :value do
        optional :bool_value, :bool, 3, json_name: "boolValue"
        optional :string_value, :string, 4, json_name: "stringValue"
        optional :double_value, :double, 5, json_name: "doubleValue"
        optional :object_value, :message, 6, "google.protobuf.Struct", json_name: "objectValue"
      end
    end
    add_message "schema.v1.ResolveBooleanRequest" do
      optional :flag_key, :string, 1, json_name: "flagKey"
      optional :context, :message, 2, "google.protobuf.Struct", json_name: "context"
    end
    add_message "schema.v1.ResolveBooleanResponse" do
      optional :value, :bool, 1, json_name: "value"
      optional :reason, :string, 2, json_name: "reason"
      optional :variant, :string, 3, json_name: "variant"
    end
    add_message "schema.v1.ResolveStringRequest" do
      optional :flag_key, :string, 1, json_name: "flagKey"
      optional :context, :message, 2, "google.protobuf.Struct", json_name: "context"
    end
    add_message "schema.v1.ResolveStringResponse" do
      optional :value, :string, 1, json_name: "value"
      optional :reason, :string, 2, json_name: "reason"
      optional :variant, :string, 3, json_name: "variant"
    end
    add_message "schema.v1.ResolveFloatRequest" do
      optional :flag_key, :string, 1, json_name: "flagKey"
      optional :context, :message, 2, "google.protobuf.Struct", json_name: "context"
    end
    add_message "schema.v1.ResolveFloatResponse" do
      optional :value, :double, 1, json_name: "value"
      optional :reason, :string, 2, json_name: "reason"
      optional :variant, :string, 3, json_name: "variant"
    end
    add_message "schema.v1.ResolveIntRequest" do
      optional :flag_key, :string, 1, json_name: "flagKey"
      optional :context, :message, 2, "google.protobuf.Struct", json_name: "context"
    end
    add_message "schema.v1.ResolveIntResponse" do
      optional :value, :int64, 1, json_name: "value"
      optional :reason, :string, 2, json_name: "reason"
      optional :variant, :string, 3, json_name: "variant"
    end
    add_message "schema.v1.ResolveObjectRequest" do
      optional :flag_key, :string, 1, json_name: "flagKey"
      optional :context, :message, 2, "google.protobuf.Struct", json_name: "context"
    end
    add_message "schema.v1.ResolveObjectResponse" do
      optional :value, :message, 1, "google.protobuf.Struct", json_name: "value"
      optional :reason, :string, 2, json_name: "reason"
      optional :variant, :string, 3, json_name: "variant"
    end
    add_message "schema.v1.EventStreamResponse" do
      optional :type, :string, 1, json_name: "type"
      optional :data, :message, 2, "google.protobuf.Struct", json_name: "data"
    end
    add_message "schema.v1.EventStreamRequest" do
    end
  end
end

module OpenFeature
  module FlagD
    module Provider
      module Grpc
        ResolveAllRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveAllRequest").msgclass
        ResolveAllResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveAllResponse").msgclass
        AnyFlag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.AnyFlag").msgclass
        ResolveBooleanRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveBooleanRequest").msgclass
        ResolveBooleanResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveBooleanResponse").msgclass
        ResolveStringRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveStringRequest").msgclass
        ResolveStringResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveStringResponse").msgclass
        ResolveFloatRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveFloatRequest").msgclass
        ResolveFloatResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveFloatResponse").msgclass
        ResolveIntRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveIntRequest").msgclass
        ResolveIntResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveIntResponse").msgclass
        ResolveObjectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveObjectRequest").msgclass
        ResolveObjectResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ResolveObjectResponse").msgclass
        EventStreamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.EventStreamResponse").msgclass
        EventStreamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.EventStreamRequest").msgclass
      end
    end
  end
end
