AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/openfeature/flagd/provider/schema/v1/**'

Lint/EmptyBlock:
  Exclude:
    - 'lib/openfeature/flagd/provider/schema/v1/**'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'openfeature-flagd-provider.gemspec'
    - 'lib/openfeature/flagd/provider/schema/v1/**'

Gemspec/RequireMFA:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/openfeature/flagd/provider/schema/v1/**'

DocumentDynamicEvalDefinition:
  Exclude:
    - lib/openfeature/flagd/provider/client.rb

Metrics/AbcSize:
  Exclude:
    - lib/openfeature/flagd/provider/**/*.rb

Metrics/MethodLength:
  Exclude:
    - lib/openfeature/flagd/provider/**/*.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/openfeature/flagd/provider/**/*.rb
