source "https://rubygems.org"

gemspec

gem "flagsmith", "~> 4.3"
gem "rake", "~> 13.0"
gem "rspec", "~> 3.12.0"
gem "webmock", "~> 3.0"
gem "standard", "~> 1.0"
gem "rubocop", "~> 1.0"
gem "simplecov", "~> 0.22"
