version: '3.7'

services:
  flagd:
    image: ghcr.io/open-feature/flagd:v0.17.0@sha256:c9f21380dfe51d3ad662a116bc350c7692dead7a8d1e640aa0f6b40cd3d966df
    ports:
      - '127.0.0.1:8013:8013'
    volumes:
      - ./:/etc/flagd
    command: start -x --uri file:./etc/flagd/flags.json
